const encodeConfig=obj=>btoa(unescape(encodeURIComponent(JSON.stringify(obj))));const decodeConfig=b64=>{try{return JSON.parse(decodeURIComponent(escape(atob(b64))))}catch(e){return null}};
const defaultPrizes=[{name:'咖啡兌換券',emoji:'☕️'},{name:'神秘小禮物',emoji:'🎁'},{name:'加薪 10 元',emoji:'💰'},{name:'擁抱一個',emoji:'🤗'},{name:'今天早退 10 分鐘',emoji:'🏃'},{name:'指定歌單播放權',emoji:'🎶'},{name:'午餐我請半份',emoji:'🍱'},{name:'稱讚 3 句',emoji:'🌟'},{name:'拍立得合照',emoji:'📸'}];
const state={title:'抽抽樂',prizes:structuredClone(defaultPrizes),allowRepeat:false,shuffleOnStart:true,coverDataUrl:null,opened:new Set()};
const el={cover:document.getElementById('cover'),game:document.getElementById('game'),grid:document.getElementById('grid'),titleInput:document.getElementById('gameTitle'),titleDisplay:document.getElementById('titleDisplay'),coverInput:document.getElementById('coverInput'),coverImage:document.getElementById('coverImage'),coverFallback:document.querySelector('.cover-image-fallback'),startBtn:document.getElementById('startBtn'),resetBtn:document.getElementById('resetBtn'),backBtn:document.getElementById('backBtn'),editBtn:document.getElementById('editPrizesBtn'),editDialog:document.getElementById('editDialog'),editGrid:document.getElementById('editGrid'),allowRepeat:document.getElementById('allowRepeat'),shuffleOnStart:document.getElementById('shuffleOnStart'),savePrizesBtn:document.getElementById('savePrizesBtn'),prizeDialog:document.getElementById('prizeDialog'),prizeEmoji:document.getElementById('prizeEmoji'),prizeName:document.getElementById('prizeName'),closePrizeBtn:document.getElementById('closePrizeBtn'),shareBtn:document.getElementById('shareBtn'),openedCount:document.getElementById('openedCount'),importBtn:document.getElementById('importBtn'),importDialog:document.getElementById('importDialog'),importText:document.getElementById('importText'),applyImportBtn:document.getElementById('applyImportBtn'),};
function init(){if(location.hash.length>1){const conf=decodeConfig(location.hash.slice(1));if(conf)Object.assign(state,conf);}el.titleInput.value=state.title||'';if(state.coverDataUrl){el.coverImage.src=state.coverDataUrl;el.coverImage.style.display='block';el.coverFallback.style.display='none';}renderEditGrid();el.allowRepeat.checked=!!state.allowRepeat;el.shuffleOnStart.checked=state.shuffleOnStart!==false;}document.addEventListener('DOMContentLoaded',init);
el.coverInput.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{state.coverDataUrl=reader.result;el.coverImage.src=state.coverDataUrl;el.coverImage.style.display='block';el.coverFallback.style.display='none';};reader.readAsDataURL(file);});
el.editBtn.addEventListener('click',()=>{renderEditGrid();el.editDialog.showModal();});
el.startBtn.addEventListener('click',()=>{state.title=el.titleInput.value.trim()||'抽抽樂';startGame();});
el.importBtn.addEventListener('click',()=>{el.importText.value='';el.importDialog.showModal();});el.applyImportBtn?.addEventListener('click',ev=>{if(ev.submitter?.value!=='apply')return;ev.preventDefault();let text=el.importText.value.trim();if(!text)return;const hash=text.includes('#')?text.split('#').pop():text;const conf=decodeConfig(hash);if(!conf){alert('解析失敗，請確認內容是否正確。');return;}Object.assign(state,conf);el.titleInput.value=state.title||'';if(state.coverDataUrl){el.coverImage.src=state.coverDataUrl;el.coverImage.style.display='block';el.coverFallback.style.display='none';}renderEditGrid();el.allowRepeat.checked=!!state.allowRepeat;el.shuffleOnStart.checked=state.shuffleOnStart!==false;el.importDialog.close();});
function renderEditGrid(){el.editGrid.innerHTML='';state.prizes.forEach((p,i)=>{const row=document.createElement('div');row.className='edit-item';row.innerHTML=`<input type="text" class="name" placeholder="獎品名稱 #${i+1}" value="${p.name??''}"/><input type="text" class="emoji" placeholder="Emoji" value="${p.emoji??''}"/>`;el.editGrid.appendChild(row);});}
el.savePrizesBtn.addEventListener('click',ev=>{if(ev.submitter?.value!=='save')return;ev.preventDefault();const rows=Array.from(el.editGrid.querySelectorAll('.edit-item'));const prizes=rows.map(r=>({name:r.querySelector('.name').value.trim()||'神秘獎品',emoji:r.querySelector('.emoji').value.trim()||'🎁'}));state.prizes=prizes.slice(0,9);state.allowRepeat=el.allowRepeat.checked;state.shuffleOnStart=el.shuffleOnStart.checked;el.editDialog.close();});
function startGame(){state.opened=new Set();el.openedCount.textContent='0';el.titleDisplay.textContent=state.title||'抽抽樂';const indexes=[...Array(9).keys()];const order=state.shuffleOnStart?shuffle(indexes):indexes;el.grid.innerHTML='';order.forEach((idx,cellIdx)=>{const prize=state.prizes[idx]||defaultPrizes[idx];const card=createCard(cellIdx,prize);el.grid.appendChild(card);});showScreen('game');}
function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function createCard(cellIndex,prize){const card=document.createElement('div');card.className='card';card.dataset.index=String(cellIndex);card.innerHTML=`<div class="back"><div class="label">點我抽！</div></div><div class="front" style="display:none;"><div class="prize"><div class="emoji">${escapeHtml(prize.emoji||'🎁')}</div><div class="name">${escapeHtml(prize.name||'神秘獎品')}</div></div></div><div class="shards"></div>`;prepareShards(card);card.addEventListener('click',()=>{if(card.classList.contains('opened'))return;shatter(card);reveal(card,prize);});return card;}
function prepareShards(card){const shards=card.querySelector('.shards');shards.innerHTML='';const positions=[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]];positions.forEach(([x,y])=>{const s=document.createElement('div');s.className='shard';s.style.left=`${x*33.34}%`;s.style.top=`${y*33.34}%`;const tx=(Math.random()*160-80)+'px';const ty=(Math.random()*-160-40)+'px';const rot=(Math.random()*540-270)+'deg';s.style.setProperty('--tx',tx);s.style.setProperty('--ty',ty);s.style.setProperty('--rot',rot);shards.appendChild(s);});}
function shatter(card){card.classList.add('break');setTimeout(()=>{const shards=card.querySelector('.shards');shards.innerHTML='';},950);}
function reveal(card,prize){const back=card.querySelector('.back');const front=card.querySelector('.front');back.style.display='none';front.style.display='grid';card.classList.add('opened');state.opened.add(card.dataset.index);document.getElementById('openedCount').textContent=String(state.opened.size);el.prizeEmoji.textContent=prize.emoji||'🎁';el.prizeName.textContent=prize.name||'神秘獎品';el.prizeDialog.showModal();}
el.closePrizeBtn.addEventListener('click',()=>el.prizeDialog.close());
el.resetBtn.addEventListener('click',()=>{if(confirm('確定要重置？所有已開的獎會清空。')){startGame();}});
el.backBtn.addEventListener('click',()=>{showScreen('cover');});
function showScreen(name){el.cover.classList.toggle('visible',name==='cover');el.game.classList.toggle('visible',name==='game');}
el.shareBtn.addEventListener('click',async()=>{const config={title:state.title,prizes:state.prizes,allowRepeat:!!state.allowRepeat,shuffleOnStart:!!state.shuffleOnStart,coverDataUrl:state.coverDataUrl||null,};const hash=encodeConfig(config);const url=location.origin+location.pathname+'#'+hash;try{if(navigator.share){await navigator.share({title:state.title||'抽抽樂',url});}else{await navigator.clipboard.writeText(url);alert('已複製分享連結到剪貼簿！');}}catch(e){prompt('複製下面的分享連結：',url);}});
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
